---
- name: Enable IPA/SSSD SSH authorized keys integration (optional)
  hosts: all
  become: true
  tasks:
    - name: Install SSSD SSH helper
      ansible.builtin.apt:
        name:
          - sssd
          - sssd-tools
          - libnss-sss
          - libpam-sss
          - sssd-ssh
        state: present
        update_cache: yes
        lock_timeout: 180

    - name: Ensure sshd uses sss_ssh_authorizedkeys (Ubuntu)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^{{ item.key }}\\b"
        line: "{{ item.key }} {{ item.value }}"
        create: no
      loop:
        - { key: "AuthorizedKeysCommand", value: "/usr/bin/sss_ssh_authorizedkeys" }
        - { key: "AuthorizedKeysCommandUser", value: "nobody" }
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted
