---
- name: Rocky update report (no changes)
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Show applicable advisories (summary)
      ansible.builtin.command: dnf -q updateinfo summary
      register: updateinfo_summary
      changed_when: false
      failed_when: false

    - name: List security advisories (if any)
      ansible.builtin.command: dnf -q updateinfo list security
      register: updateinfo_security
      changed_when: false
      failed_when: false

    - name: Print report
      ansible.builtin.debug:
        msg:
          - "updateinfo_summary:"
          - "{{ updateinfo_summary.stdout_lines | default([]) }}"
          - "security_advisories:"
          - "{{ updateinfo_security.stdout_lines | default([]) }}"
