- name: Weekly Ubuntu full patching (update + dist-upgrade)
  hosts: all
  become: true
  gather_facts: true

  vars:
    reboot_if_required: false
    apt_lock_timeout: 180
    apt_cache_valid_time: 0      # 0 = always refresh cache on weekly run (safe)
    upgrade_mode: "dist"         # FULL upgrade weekly

  tasks:
    - name: Sanity check - Ubuntu/Debian only
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == "Debian"
        fail_msg: "This playbook only supports Debian/Ubuntu hosts."

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time }}"
        lock_timeout: "{{ apt_lock_timeout }}"
      register: apt_cache

    - name: Ensure unattended-upgrades tooling is present (optional but recommended)
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - update-notifier-common
        state: present
        lock_timeout: "{{ apt_lock_timeout }}"

    - name: Enable periodic unattended upgrades (between weekly runs)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: "0644"
        owner: root
        group: root
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";

    - name: Full upgrade now (dist-upgrade)
      ansible.builtin.apt:
        upgrade: "{{ upgrade_mode }}"
        autoremove: yes
        autoclean: yes
        lock_timeout: "{{ apt_lock_timeout }}"
      register: apt_upgrade

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: rr

    - name: Reboot if required (optional)
      ansible.builtin.reboot:
        msg: "Reboot triggered by weekly full patching"
        reboot_timeout: 1800
      when: reboot_if_required and rr.stat.exists

    - name: Summary for AWX output
      ansible.builtin.debug:
        msg:
          - "apt_cache_updated={{ apt_cache.changed | default(false) }}"
          - "apt_changed={{ apt_upgrade.changed | default(false) }}"
          - "reboot_required={{ rr.stat.exists | default(false) }}"
