---
- name: Validate AWX connectivity + passwordless sudo
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping (no sudo)
      ansible.builtin.ping:

    - name: Verify passwordless sudo
      ansible.builtin.command: sudo -n true
      register: sudotest
      changed_when: false

    - name: Show sudo result
      ansible.builtin.debug:
        msg: "SUDO_OK"
