---
- name: Validate AWX connectivity + passwordless sudo
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping (no sudo)
      ansible.builtin.ping:

    - name: Verify passwordless sudo (systemctl allowed)
      ansible.builtin.command: sudo -n /usr/bin/systemctl is-system-running
      register: sudotest
      changed_when: false
      failed_when: false

    - name: Show sudo result
      ansible.builtin.debug:
        msg: "SUDO_OK"
